#include <stdio.h>
#include <string.h>
#include "tvmgen_default.h"
#include "input_data.h"
#include "output_data.h"
#include "xtimer.h"
int main(void)
{

    uint32_t start, end;
    (void) puts("Welcome to RIOT!");
    (void) puts("This is Inference App for LeNet5 generated by uTVM.");
    struct tvmgen_default_inputs inputs = {
      .serving_default_input_0 = input_data,
    };
    struct tvmgen_default_outputs outputs = {
      .PartitionedCall_0 = output_data,
    };
    start =  xtimer_now_usec();
    int ret_val = tvmgen_default_run(&inputs, &outputs);
    end =  xtimer_now_usec();
    printf("usec: %d \n", (end - start));
    return 0;
}